# Generated by Django 3.1.3 on 2020-11-20 20:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('empId', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('mobile', models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999999999)])),
                ('dob', models.DateField(null=True)),
                ('city', models.CharField(max_length=200)),
                ('address', models.TextField()),
            ],
        ),
    ]
