# Generated by Django 3.1.3 on 2020-11-20 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_managerr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='managerr',
            name='birth_date',
        ),
    ]
