# Generated by Django 3.1.3 on 2020-11-20 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_remove_managerr_birth_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='managerr',
            old_name='firstname',
            new_name='fullname',
        ),
        migrations.RemoveField(
            model_name='managerr',
            name='lastname',
        ),
    ]
