# Generated by Django 3.1.3 on 2020-11-20 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_auto_20201121_0420'),
    ]

    operations = [
        migrations.RenameField(
            model_name='managerr',
            old_name='fullname',
            new_name='firstname',
        ),
        migrations.AddField(
            model_name='managerr',
            name='lastname',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
