# Generated by Django 3.1.3 on 2020-11-21 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_auto_20201121_0441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='managerr',
            name='id',
        ),
        migrations.RemoveField(
            model_name='managerr',
            name='user',
        ),
        migrations.AddField(
            model_name='managerr',
            name='email',
            field=models.EmailField(default='', max_length=100, primary_key=True, serialize=False),
        ),
    ]
